// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using zeynerp.Infrastructure.Data.Contexts;

#nullable disable

namespace zeynerp.Infrastructure.Data.Migrations.TenantDb
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20250624113426_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CariCariTur", b =>
                {
                    b.Property<int>("CariTurlerId")
                        .HasColumnType("int");

                    b.Property<int>("CarilerId")
                        .HasColumnType("int");

                    b.HasKey("CariTurlerId", "CarilerId");

                    b.HasIndex("CarilerId");

                    b.ToTable("CariCariTur");
                });

            modelBuilder.Entity("zeynerp.Core.Entities.SatinalmaYonetimi.MalzemeTalep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Birim")
                        .HasColumnType("int");

                    b.Property<double>("Boyut1")
                        .HasColumnType("float");

                    b.Property<double>("Boyut2")
                        .HasColumnType("float");

                    b.Property<double>("Boyut3")
                        .HasColumnType("float");

                    b.Property<double>("Boyut4")
                        .HasColumnType("float");

                    b.Property<double>("Kg")
                        .HasColumnType("float");

                    b.Property<double>("M")
                        .HasColumnType("float");

                    b.Property<double>("M2")
                        .HasColumnType("float");

                    b.Property<int?>("MalzemeTalepleriId")
                        .HasColumnType("int");

                    b.Property<double>("Mm")
                        .HasColumnType("float");

                    b.Property<int>("StokGrupId")
                        .HasColumnType("int");

                    b.Property<int>("StokId")
                        .HasColumnType("int");

                    b.Property<int>("StokOzellikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MalzemeTalepleriId");

                    b.HasIndex("StokGrupId");

                    b.HasIndex("StokId");

                    b.HasIndex("StokOzellikId");

                    b.ToTable("MalzemeTalepler");
                });

            modelBuilder.Entity("zeynerp.Core.Entities.SatinalmaYonetimi.MalzemeTalepleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CariId")
                        .HasColumnType("int");

                    b.Property<int>("CariYetkiliId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CariId");

                    b.HasIndex("CariYetkiliId");

                    b.ToTable("MalzemeTalepleri");
                });

            modelBuilder.Entity("zeynerp.Core.Entities.Tanimlamalar.Birim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Birimler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Yok",
                            Order = 1,
                            Status = 1,
                            Unit = "Yok"
                        });
                });

            modelBuilder.Entity("zeynerp.Core.Entities.Tanimlamalar.Cari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EPosta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaturaAdresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KisaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VergiDairesi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VergiNumarasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cariler");
                });

            modelBuilder.Entity("zeynerp.Core.Entities.Tanimlamalar.CariTur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CariTurler");
                });

            modelBuilder.Entity("zeynerp.Core.Entities.Tanimlamalar.CariYetkili", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdiSoyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CariId")
                        .HasColumnType("int");

                    b.Property<string>("EPosta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CariId");

                    b.ToTable("CariYetkililer");
                });

            modelBuilder.Entity("zeynerp.Core.Entities.Tanimlamalar.Stok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ayrac1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ayrac2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ayrac3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ayrac4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BirimFiyatHesaplama")
                        .HasColumnType("int");

                    b.Property<int>("BirimId")
                        .HasColumnType("int");

                    b.Property<string>("Boyut1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Boyut2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Boyut3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Boyut4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Fire1")
                        .HasColumnType("bit");

                    b.Property<bool?>("Fire2")
                        .HasColumnType("bit");

                    b.Property<bool?>("Fire3")
                        .HasColumnType("bit");

                    b.Property<bool?>("Fire4")
                        .HasColumnType("bit");

                    b.Property<string>("KGFormül")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KutuSayisi")
                        .HasColumnType("int");

                    b.Property<string>("M2Formül")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MFormül")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MMFormül")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oncul1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oncul2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oncul3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oncul4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SatinAlma")
                        .HasColumnType("bit");

                    b.Property<bool>("Sertifika")
                        .HasColumnType("bit");

                    b.Property<int?>("Siralama1")
                        .HasColumnType("int");

                    b.Property<int?>("Siralama2")
                        .HasColumnType("int");

                    b.Property<int?>("Siralama3")
                        .HasColumnType("int");

                    b.Property<int?>("Siralama4")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StokGrupId")
                        .HasColumnType("int");

                    b.Property<Guid>("StokSorumluId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StokGrupId");

                    b.ToTable("Stoklar");
                });

            modelBuilder.Entity("zeynerp.Core.Entities.Tanimlamalar.StokGrup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StokGruplar");
                });

            modelBuilder.Entity("zeynerp.Core.Entities.Tanimlamalar.StokOzellik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<double>("OzgulAgirlik")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StokOzellikler");
                });

            modelBuilder.Entity("zeynerp.Core.Entities.Tanimlamalar.TeslimatAdres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CariId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CariId");

                    b.ToTable("TeslimatAdresleri");
                });

            modelBuilder.Entity("CariCariTur", b =>
                {
                    b.HasOne("zeynerp.Core.Entities.Tanimlamalar.CariTur", null)
                        .WithMany()
                        .HasForeignKey("CariTurlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("zeynerp.Core.Entities.Tanimlamalar.Cari", null)
                        .WithMany()
                        .HasForeignKey("CarilerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("zeynerp.Core.Entities.SatinalmaYonetimi.MalzemeTalep", b =>
                {
                    b.HasOne("zeynerp.Core.Entities.SatinalmaYonetimi.MalzemeTalepleri", "MalzemeTalepleri")
                        .WithMany("MalzemeTalepler")
                        .HasForeignKey("MalzemeTalepleriId");

                    b.HasOne("zeynerp.Core.Entities.Tanimlamalar.StokGrup", "StokGrup")
                        .WithMany()
                        .HasForeignKey("StokGrupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("zeynerp.Core.Entities.Tanimlamalar.Stok", "Stok")
                        .WithMany()
                        .HasForeignKey("StokId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("zeynerp.Core.Entities.Tanimlamalar.StokOzellik", "StokOzellik")
                        .WithMany()
                        .HasForeignKey("StokOzellikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MalzemeTalepleri");

                    b.Navigation("Stok");

                    b.Navigation("StokGrup");

                    b.Navigation("StokOzellik");
                });

            modelBuilder.Entity("zeynerp.Core.Entities.SatinalmaYonetimi.MalzemeTalepleri", b =>
                {
                    b.HasOne("zeynerp.Core.Entities.Tanimlamalar.Cari", "Cari")
                        .WithMany()
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("zeynerp.Core.Entities.Tanimlamalar.CariYetkili", "CariYetkili")
                        .WithMany()
                        .HasForeignKey("CariYetkiliId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cari");

                    b.Navigation("CariYetkili");
                });

            modelBuilder.Entity("zeynerp.Core.Entities.Tanimlamalar.CariYetkili", b =>
                {
                    b.HasOne("zeynerp.Core.Entities.Tanimlamalar.Cari", "Cari")
                        .WithMany("CariYetkililer")
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cari");
                });

            modelBuilder.Entity("zeynerp.Core.Entities.Tanimlamalar.Stok", b =>
                {
                    b.HasOne("zeynerp.Core.Entities.Tanimlamalar.StokGrup", "StokGrup")
                        .WithMany()
                        .HasForeignKey("StokGrupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StokGrup");
                });

            modelBuilder.Entity("zeynerp.Core.Entities.Tanimlamalar.TeslimatAdres", b =>
                {
                    b.HasOne("zeynerp.Core.Entities.Tanimlamalar.Cari", "Cari")
                        .WithMany("TeslimatAdresler")
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cari");
                });

            modelBuilder.Entity("zeynerp.Core.Entities.SatinalmaYonetimi.MalzemeTalepleri", b =>
                {
                    b.Navigation("MalzemeTalepler");
                });

            modelBuilder.Entity("zeynerp.Core.Entities.Tanimlamalar.Cari", b =>
                {
                    b.Navigation("CariYetkililer");

                    b.Navigation("TeslimatAdresler");
                });
#pragma warning restore 612, 618
        }
    }
}
